CREATE DATABASE BANKINGDB;
USE  BANKINGDB;

-- CUSTOMER TABLE
CREATE TABLE CUSTOMERS(
CUSTOMERID INT auto_increment PRIMARY KEY,
CUSTOMERNAME VARCHAR(100) NOT NULL,
GENDER ENUM('MALE','FEMALE','OTHER'),
DATEOFBIRTH DATE,
PHONENUMBER VARCHAR(15) UNIQUE,
EMAIL VARCHAR(100) UNIQUE,
CITY VARCHAR(50),
STATE VARCHAR(50),
CUSTOMERSTATUS ENUM('ACTIVE','INACTIVE') DEFAULT 'ACTIVE'
);

-- BRANCHES TABLE
CREATE TABLE Branches (
    BranchId INT AUTO_INCREMENT PRIMARY KEY,
    BranchName VARCHAR(100) NOT NULL,
    BranchCode VARCHAR(10) UNIQUE,
    City VARCHAR(50),
    State VARCHAR(50),
    IFSCCode VARCHAR(15) UNIQUE
);

-- ACCOUNTS TABLE
CREATE TABLE Accounts (
    AccountId INT AUTO_INCREMENT PRIMARY KEY,
    CustomerId INT,
    BranchId INT,
    AccountNumber VARCHAR(20) UNIQUE,
    AccountType ENUM('Savings','Current','Fixed Deposit'),
    OpenDate DATE,
    Balance DECIMAL(10,2),
    AccountStatus ENUM('Active','Closed','Frozen') DEFAULT 'Active',
    FOREIGN KEY (CustomerId) REFERENCES Customers(CustomerId),
    FOREIGN KEY (BranchId) REFERENCES Branches(BranchId)
);

-- TRANSACTIONS TABLE
CREATE TABLE Transactions (
    TransactionId INT AUTO_INCREMENT PRIMARY KEY,
    AccountId INT,
    TransactionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    TransactionType ENUM('Deposit','Withdrawal','Transfer'),
    Amount DECIMAL(10,2),
    Description VARCHAR(255),
    FOREIGN KEY (AccountId) REFERENCES Accounts(AccountId)
);

-- LOANS TABLE
CREATE TABLE Loans (
    LoanId INT AUTO_INCREMENT PRIMARY KEY,
    CustomerId INT,
    BranchId INT,
    LoanType ENUM('Home Loan','Car Loan','Personal Loan','Education Loan'),
    LoanAmount DECIMAL(12,2),
    InterestRate DECIMAL(5,2),
    LoanStartDate DATE,
    LoanStatus ENUM('Approved','Pending','Closed'),
    FOREIGN KEY (CustomerId) REFERENCES Customers(CustomerId),
    FOREIGN KEY (BranchId) REFERENCES Branches(BranchId)
);


-- ACCOUNTAUDIT TABLE
CREATE TABLE AccountAudit (
    AuditId INT AUTO_INCREMENT PRIMARY KEY,
    AccountId INT,
    ActionType VARCHAR(50),
    OldBalance DECIMAL(10,2),
    NewBalance DECIMAL(10,2),
    ActionDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Remarks VARCHAR(255)
);

-- DATA INSERTION
INSERT INTO Customers (CustomerName, Gender, PhoneNumber, Email, City, State)
VALUES 
('Sourav', 'Male', '9876543210', 'sourav@mail.com', 'Ranchi', 'Jharkhand'),
('Rahul', 'Male', '9876543211', 'rahul@mail.com', 'Chennai', 'Tamil Nadu');

INSERT INTO Branches (BranchName, BranchCode, City, State, IFSCCode)
VALUES 
('Main Branch', 'BR001', 'Ranchi', 'Jharkhand', 'IFSC0001'),
('City Branch', 'BR002', 'Chennai', 'Tamil Nadu', 'IFSC0002');

INSERT INTO Accounts (CustomerId, BranchId, AccountNumber, AccountType, OpenDate, Balance)
VALUES 
(1,1,'ACC001','Savings','2023-01-01',50000),
(2,2,'ACC002','Savings','2023-02-01',150000);

INSERT INTO Loans (CustomerId, BranchId, LoanType, LoanAmount, InterestRate, LoanStartDate, LoanStatus)
VALUES 
(1,1,'Personal Loan',50000,10.5,'2023-03-01','Approved'),
(2,2,'Home Loan',500000,8.5,'2023-04-01','Pending');

SELECT * FROM CUSTOMERS;
SELECT * FROM BRANCHES;
SELECT * FROM LOANS;
SELECT * FROM ACCOUNTS;

-- SUBQUERY
-- 1
SELECT * FROM CUSTOMERS WHERE CUSTOMERID IN 
(SELECT CUSTOMERID FROM ACCOUNTS WHERE BALANCE>(SELECT AVG(BALANCE) FROM ACCOUNTS));


-- 2
SELECT * FROM CUSTOMERS WHERE CUSTOMERID IN 
(SELECT CUSTOMERID FROM LOANS WHERE LOANAMOUNT > (SELECT MAX(LOANAMOUNT)FROM LOANS WHERE LOANTYPE='PERSONAL LOAN'));

-- 3
SELECT * FROM ACCOUNTS WHERE BRANCHID IN(
SELECT BRANCHID FROM BRANCHES WHERE CITY='CHENNAI'
 );

-- 4
SELECT * FROM CUSTOMERS WHERE CUSTOMERID NOT IN 
(
SELECT CUSTOMERID FROM LOANS
) ;

-- 5
SELECT CUSTOMERID FROM ACCOUNTS 
WHERE ACCOUNTID in(
SELECT ACCOUNTID FROM TRANSACTIONS GROUP BY ACCOUNTID
HAVING SUM(AMOUNT) > (SELECT  SUM(AMOUNT) FROM TRANSACTIONS  WHERE ACCOUNTID IN (SELECT ACCOUNTID FROM ACCOUNTS WHERE CUSTOMERID =1))
);

-- 6
SELECT * FROM Branches WHERE BranchId IN (
SELECT BranchId FROM Accounts GROUP BY BranchId HAVING COUNT(*) > 
(
SELECT AVG(AccountCount)FROM ( SELECT COUNT(*) AS AccountCount  FROM Accounts 
 GROUP BY BranchId ) AS temp )
);


-- 7
SELECT * FROM ACCOUNTS WHERE BALANCE =
(SELECT MAX(BALANCE)FROM ACCOUNTS WHERE BALANCE < (SELECT MAX(BALANCE ) FROM ACCOUNTS)
) ;

-- 8
select * FROM CUSTOMERS WHERE CUSTOMERID IN (SELECT CUSTOMERID FROM ACCOUNTS WHERE OPENDATE=(SELECT MIN(OPENDATE) FROM ACCOUNTS));
 
 
 -- 9
 SELECT * FROM LOANS WHERE CUSTOMERID IN (SELECT CUSTOMERID FROM ACCOUNTS WHERE ACCOUNTTYPE ='SAVINGS');
 
 
 -- 10
 SELECT * FROM CUSTOMERS WHERE CUSTOMERID IN (SELECT CUSTOMERID FROM ACCOUNTS GROUP BY CUSTOMERID HAVING COUNT(*)>1);
 
 
 -- VIEWS
 -- 1
 CREATE VIEW  VW_CUSTOMERACCOUNTETAILS AS
 SELECT C.CUSTOMERID,C.CUSTOMERNAME,A.ACCOUNTNUMBER,A.ACCOUNTTYPE,A.BALANCE,A.ACCOUNTSTATUS
 FROM CUSTOMERS C 
 JOIN ACCOUNTS A 
 ON A.CUSTOMERID=C.CUSTOMERID;
 DROP VIEW VW_CUSTOMERACCOUNTETAILS;
 SELECT * FROM VW_CUSTOMERACCOUNTETAILS ;

 -- 2
CREATE VIEW VW_BRANCHACCOUNT  AS
SELECT  B.BRANCHNAME,COUNT(A.ACCOUNTID) AS TOTALACCOUNTS,SUM(A.BALANCE) AS TOTALBALANCE
FROM BRANCHES B
JOIN ACCOUNTS A
ON B.BRANCHID=A.BRANCHID
GROUP BY BRANCHNAME;
 
 
 
 SELECT * FROM VW_BRANCHACCOUNT;
 
 
 
 -- 3
 CREATE VIEW VW_LOANCUSTOMERDETAILS AS 
 SELECT C.CUSTOMERNAME,L.LOANTYPE,L.LOANAMOUNT,L.INTERESTRATE,L.LOANSTATUS,B.BRANCHNAME
 FROM CUSTOMERS C 
 JOIN LOANS K ON C.CUSTOMERID=L.CUSTOMERID
 JOIN BRANCHES B ON L.BRANCHID = B.BRANCHID;
 
 
 -- 4
 CREATE VIEW VW_HIGHVALUEACCOUNTS AS 
 SELECT * FROM ACCOUNTS WHERE BALANCE>100000;

SELECT * FROM VW_HIGHVALUEACCOUNTS;

-- 5
CREATE VIEW  VW_DAILYTRANSACTIONS AS
SELECT A.ACCOUNTNUMBER,T.TRANSACTIONDATE,T.TRANSACTIONTYPE,T.DESCRIPTION
FROM ACCOUNTS A 
JOIN TRANSACTIONS T ON
T.ACCOUNTID=A.ACCOUNTID;

SELECT * FROM VW_DAILYTRANSACTIONS;


-- 6
CREATE VIEW VW_ACTIVECUSTOMERS AS 
SELECT  * FROM ACCOUNTS WHERE ACCOUNTSTATUS='ACTIVE';


SELECT * FROM VW_ACTIVECUSTOMERS;


 -- 7
CREATE VIEW VW_APPROVEDLOANS AS 
SELECT  * FROM LOANS WHERE LOANSTATUS='APPROVED';
 
 -- 8
 CREATE VIEW COMBINEDVIEW AS 
sELECT c.CustomerName, a.AccountNumber, b.BranchName
FROM CUSTOMERS C JOIN ACCOUNTS A ON
 C.CUSTOMERID=A.CUSTOMERID
 JOIN BRANCHES B 
 ON A.BRANCHID=B.BRANCHID;
 
 SELECT * FROM COMBINEDVIEW;
 
 -- 9

  SELECT * FROM COMBINEDVIEW;
 
 
 UPDATE vw_ActiveCustomers SET City='gODDA' WHERE CustomerId=2;
 
 
 INSERT INTO vw_ActiveCustomers(CustomerName, PhoneNumber, Email)
VALUES ('SOURAV KUMAR','987654321','sourav@mail.com');
 
 
 
 -- 10
 CREATE VIEW vw_BranchBalanceSummary AS
SELECT BranchId, SUM(Balance) AS TotalBalance
FROM Accounts
GROUP BY BranchId;
 
 
 -- stored procedure
 -- 1
 drop procedure getallcustomers;
 create procedure getallcustomers()
 select * from customers;
 
 call getallcustomers()
 
 -- 2
 DELIMITER //
 CREATE PROCEDURE GetAccountsByCustomer(IN p_CustomerId INT)
 BEGIN 
 SELECT * FROM ACCOUNTS WHERE CUSTOMERID=p_CUSTOMERID;
 END //
 DELIMITER ;
 
CALL GetAccountsByCustomer(101);

-- 3


 DELIMITER //
 CREATE PROCEDURE GetBranchTotalBalance(IN p_BranchId INT)
 BEGIN 
 SELECT sum(balance) FROM branches WHERE branchid=p_branchid;
 END //
 DELIMITER ;


-- 4

 DELIMITER //
 CREATE PROCEDURE GetApprovedLoanCount(OUT p_TotalCount INT)
 BEGIN 
 SELECT count (loanstatus) FROM loans WHERE loanstatus='approved';
 END //
 DELIMITER ;


-- 5

























