Create database ECOMMERCEDB;

USE ECOMMERCEDB;

CREATE TABLE CUSTOMERS(
CUSTOMERID INT,
CUSTOMERNAME VARCHAR(50),
CITY VARCHAR(40),
EMAIL VARCHAR(100) 
);

SELECT * FROM CUSTOMERS;
DESC CUSTOMERS;

CREATE TABLE PRODUCTS(
PRODUCTID INT,
PRODUCTNAME VARCHAR(50),
CATEGORY VARCHAR(40),
PRICE INT
);


SELECT * FROM PRODUCTS;
DESC PRODUCTS;


CREATE TABLE ORDERS(
ORDERID INT,
CUSTOMERID INT,
ORDERDATE DATE,
TOTALAMOUNT INT
);

SELECT * FROM ORDERS;
DESC ORDERS;

CREATE TABLE ORDERITEMS(
ORDERITEMID INT,
ORDERID INT,
PRODUCTID INT,
QUANTITY INT
);


SELECT * FROM ORDERITEMS;
DESC ORDERITEMS;

-- SECTION B - CONSTRAINTS

ALTER TABLE Customers MODIFY CustomerId INT NOT NULL AUTO_INCREMENT;
 Alter table PRODUCTS modify PRODUCTID int not null auto_increment, add primary key(PRODUCTID);
 Alter table ORDERS modify ORDERID int not null auto_increment, add primary key(ORDERID);
 Alter table ORDERITEMS modify ORDERITEMID int not null auto_increment, add primary key(ORDERITEMID);


ALTER TABLE CUSTOMERS ADD PRIMARY KEY(CUSTOMERID);
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_CUSTOMERS
FOREIGN KEY(CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);


ALTER TABLE ORDERS ADD PRIMARY KEY(ORDERID);
ALTER TABLE ORDERITEMS
ADD CONSTRAINT FK_ORDERITEMS_ORDERS
FOREIGN KEY(ORDERID)
REFERENCES ORDERS(ORDERID);

ALTER TABLE ORDERITEMS
ADD CONSTRAINT FK_ORDERITEMS_PRODCUTS
FOREIGN KEY(PRODUCTID)
REFERENCES PRODUCTS(PRODUCTID);

-- END

-- SECTION C - DATA INSERTION

-- 13
INSERT INTO Customers  VALUES
(1,'Sourav', 'Delhi', 'sourav@gmail.com'),
(2,'Sachin', 'Bangalore', 'sachin@gmail.com'),
(3,'Sintu', 'Chennai', 'sintu@gmail.com'),
(4,'Mintu', 'Mumbai', 'mintu@gmail.com'),
(5,'Mehul', 'Bangalore', 'mehul@gmail.com');


-- 14
INSERT INTO Products (ProductName, Category, Price) VALUES
('Laptop', 'Electronics', 60000),
('Chair', 'Furniture', 3000),
('Mobile', 'Electronics', 20000),
('Table', 'Furniture', 7000),
('Mouse', 'Accessories', 500);
 

-- 15
INSERT INTO Orders (CustomerId, OrderDate, TotalAmount) VALUES
(1, '2024-02-10', 30000),
(2, '2024-03-05', 5000),
(3, '2024-04-01', 25000),
(1, '2024-05-10', 70000),
(4, '2024-06-15', 15000);

-- 16
INSERT INTO OrderItems (OrderId, ProductId, Quantity) VALUES
(1,1,1),
(1,3,1),
(2,2,2),
(3,4,1),
(4,1,1),
(5,5,3);

-- 17
INSERT INTO CUSTOMERS VALUES(6,'ADITYA','DELHI',NULL);

-- SECTION D ARITHMETIC OPERATIONS

-- 18
SELECT QUANTITY*1000 AS TOTAL FROM ORDERITEMS; 

-- 19
SELECT PRICE+500 AS UPDATED_PRICE FROM PRODUCTS;

-- 20
SELECT PRICE-200 AS DISCOUNTED_PRICE FROM PRODUCTS;

-- 21
SELECT QUANTITY, QUANTITY*2 AS UPDATED_QUANTITY FROM ORDERITEMS;

-- 22
SELECT TOTALAMOUNT/2 AS NEW_AMOUNT FROM ORDERS;


-- COMPARISON OPERATOR

-- 23
SELECT * FROM ORDERS WHERE TOTALAMOUNT>10000;

-- 24
SELECT * FROM PRODUCTS WHERE PRICE<5000;

-- 25
SELECT * FROM ORDERS WHERE TOTALAMOUNT>=25000;

-- 26
SELECT * FROM PRODUCTS WHERE PRICE<=8000;

-- 27
SELECT * FROM CUSTOMERS WHERE CITY='CHENNAI';

-- 28
SELECT * FROM CUSTOMERS WHERE CITY!='DELHI';

-- LOGICAL OPERATORS
-- 29
SELECT CUSTOMERNAME FROM CUSTOMERS WHERE CITY='BANGLORE' AND CUSTOMERNAME LIKE 'A%';

-- 30
SELECT * FROM PRODUCTS WHERE CATEGORY='ELECTRONICS' OR CATEGORY='FURNITURE';

-- 31
SELECT * FROM ORDERS WHERE TOTALAMOUNT>5000 AND TOTALAMOUNT<7000;

-- 32
SELECT * FROM CUSTOMERS WHERE CITY!= 'MUMBAI';

-- 33
SELECT * FROM PRODUCTS WHERE CATEGORY != 'ACCESSORIES'; 


-- SECTION G SPECIAL OPERATORS















