CREATE DATABASE SubqueryDemo;
USE SubqueryDemo;

CREATE TABLE Customers
(
    CustomerId INT PRIMARY KEY AUTO_INCREMENT,
    CustomerName VARCHAR(100) NOT NULL,
    City VARCHAR(50),
    Email VARCHAR(100),
    JoinDate DATE
);

CREATE TABLE Categories
(
    CategoryId INT PRIMARY KEY AUTO_INCREMENT,
    CategoryName VARCHAR(100) NOT NULL
);

CREATE TABLE Products
(
    ProductId INT PRIMARY KEY AUTO_INCREMENT,
    ProductName VARCHAR(100) NOT NULL,
    CategoryId INT,
    Price DECIMAL(10,2),
    Stock INT,
    FOREIGN KEY (CategoryId) REFERENCES Categories(CategoryId)
);

CREATE TABLE Orders
(
    OrderId INT PRIMARY KEY AUTO_INCREMENT,
    CustomerId INT,
    ProductId INT,
    OrderDate DATE,
    Quantity INT,
    TotalAmount DECIMAL(10,2),
    FOREIGN KEY (CustomerId) REFERENCES Customers(CustomerId),
    FOREIGN KEY (ProductId) REFERENCES Products(ProductId)
);

INSERT INTO Customers (CustomerName, City, Email, JoinDate)
VALUES
('Amit Sharma', 'Chennai', 'amit@gmail.com', '2024-01-10'),
('Priya Nair', 'Bangalore', 'priya@gmail.com', '2024-02-15'),
('Rahul Verma', 'Hyderabad', 'rahul@gmail.com', '2024-03-05'),
('Sneha Iyer', 'Chennai', 'sneha@gmail.com', '2024-01-25'),
('Karthik Raj', 'Mumbai', 'karthik@gmail.com', '2024-04-11');


INSERT INTO Categories (CategoryName)
VALUES
('Electronics'),
('Clothing'),
('Books'),
('Home Appliances');

INSERT INTO Products (ProductName, CategoryId, Price, Stock)
VALUES
('Laptop', 1, 75000.00, 10),
('Mobile Phone', 1, 25000.00, 25),
('T-Shirt', 2, 800.00, 100),
('Jeans', 2, 1500.00, 60),
('SQL Book', 3, 550.00, 40),
('Microwave Oven', 4, 12000.00, 8),
('Python Book', 3, 700.00, 30);


INSERT INTO Orders (CustomerId, ProductId, OrderDate, Quantity, TotalAmount)
VALUES
(1, 1, '2024-05-01', 1, 75000.00),
(2, 2, '2024-05-03', 1, 25000.00),
(3, 3, '2024-05-05', 2, 1600.00),
(1, 5, '2024-05-06', 3, 1650.00),
(4, 4, '2024-05-07', 1, 1500.00),
(2, 6, '2024-05-08', 1, 12000.00),
(3, 2, '2024-05-09', 1, 25000.00),
(5, 7, '2024-05-10', 2, 1400.00);

SELECT * FROM Customers;
SELECT * FROM Categories;
SELECT * FROM Products;
SELECT * FROM Orders;


-- 1
SELECT ProductName, PRICE FROM prodUcts WHERE PRICE > (SELECT AVG(PRICE) FROM PRODUCTS);

SELECT ProductName, Price
FROM Products
WHERE Price >
(
    SELECT AVG(Price)
    FROM Products
);

-- 2


SELECT CUSTOMERNAME,JOINDATE FROM CUSTOMERS WHERE JOINDATE>
(
SELECT MIN(JOINDATE) FROM CUSTOMERS)
;

-- MULTIPLE ROW SUBQUERY 
-- 1
SELECT PRODUCTNAME,PRICE
FROM PRODUCTS
WHERE CATEGORYID IN
(
SELECT CATEGORYID FROM CATEGORIES WHERE CATEGORYNAME IN ('ELECTRONICS','BOOKS'));

-- 2
SELECT CUSTOMERNAME FROM CUSTOMERS WHERE CUSTOMERID IN (SELECT CUSTOMERID FROM ORDERS);

-- MULTIPLE COLUMN SUBQUERY
SELECT ORDERID,CUSTOMERID,PRODUCTID,TOTALAMOUNT
FROM ORDERS
WHERE(CUSTOMERID,PRODUCTID) IN 
(
SELECT PRODUCTID,CUSTOMERID FROM ORDERS WHERE QUANTITY>=2
);

-- CORRELATED SUBQUERY
-- 1
SELECT P.PRODUCTNAME,P.PRICE,P.CATEGORYID
FROM PRODUCTS P 
WHERE P.PRICE>(SELECT AVG(P2.PRICE) FROM PRODUCTS P2
WHERE P2.CATEGORYID=P.CATEGORYID); 

-- 2

SELECT O1.CUSTOMERID,O1.ORDERID,O1.TOTALAMOUNT FROM ORDERS O1
WHERE O1.TOTALAMOUNT
>
(
SELECT AVG(O2.TOTALAMOUNT) FROM ORDERS O2 
WHERE O2.CUSTOMERID=O1.CUSTOMERID);



-- NESTED SUBQUERY
SELECT ProductName, CategoryId, Price
FROM Products
WHERE CategoryId IN
(
    SELECT DISTINCT CategoryId
    FROM Products
    WHERE ProductId IN
    (
        SELECT ProductId
        FROM Orders
        WHERE TotalAmount > 20000
    )
);

-- SUBQUERY WHERE CLAUSE
SELECT * FROM ORDERS WHERE TOTALAMOUNT >
(
SELECT AVG(TOTALAMOUNT) FROM ORDERS);

-- SUBQUERY WITH SELECT CLAUSE
-- 1
SELECT PRODUCTNAME,PRICE ,(SELECT AVG(PRICE) FROM PRODUCTS) AS AVERAGEPRICE FROM PRODUCTS;

-- 2
SELECT CUSTOMERNAME, (
SELECT COUNT(*) FROM ORDERS O WHERE O.CUSTOMERID=C.CUSTOMERID) AS TOTALORDERS FROM CUSTOMERS C;


-- SUBQUERY IN FROM CLAUSE
-- 1
SELECT AVG(CUSTOMERTOTAL) AS AVERAGECUSTOMERSPENDING
FROM
(
SELECT CUSTOMERID,SUM(TOTALAMOUNT) AS CUSTOMERTOTAL
FROM ORDERS 
GROUP BY CUSTOMERID
) AS CUSTOMERSUMMARY;


-- 2
SELECT MAX(CUSTOMERTOTAL) AS HIGHSPENDING
FROM(
SELECT CUSTOMERID,SUM(TOTALAMOUNT) AS CUSTOMERTOTAL 
FROM ORDERS GROUP BY CUSTOMERID
) AS SPENDINGDATA;

 -- 15 SCALAR SUBQUERY
 SELECT PRODUCTNAME,PRICE FROM PRODUCTS WHERE PRICE >
 (
 SELECT AVG(PRICE) FROM PRODUCTS
 );


-- SUBQUERY WITH EXISTS
SELECT CUSTOMERNAME FROM CUSTOMERS C WHERE EXISTS 
(
SELECT 1 FROM ORDERS O WHERE O.CUSTOMERID = C.CUSTOMERID
);


-- SUBQUERY WITH NOTEXISTS

SELECT CUSTOMERNAME FROM CUSTOMERS C WHERE NOT EXISTS 
(
SELECT 1 FROM ORDERS O WHERE O.CUSTOMERID = C.CUSTOMERID
);

SELECT PRODUCTNAME FROM PRODUCTS P WHERE NOT EXISTS
(
SELECT 1 FROM ORDERS O WHERE O.PRODUCTID=P.PRODUCTID
);




-- SUBQUERY WITH ALL

SELECT PRODUCTNAME ,PRICE FROM PRODUCTS WHERE PRICE > ALL
(
SELECT PRICE FROM PRODUCTS WHERE CATEGORYID=
(
SELECT CATEGORYID FROM CATEGORIES WHERE CATEGORYNAME ='BOOKS'
)
);









































